### ISSUE TITLE
data splits for comparison

### ISSUE THREAD

**Issue by heyufan1995** [MASILab/3DUX-Net#10]
Hi:
Could you provide the 5 fold data splilts of train/val/test of the Feta and Flare dataset?
So we can directly compare the results.
Thanks,
Yufan.

**Comment by leeh43** [comment]
Hi Yufan,

Thank you for your interest to our idea, I will generate and upload the .json file for each dataset in the next few commits. 

Best,
Peter

**Comment by paulzwh** [comment]
@leeh43  Hello, thanks for your work. I am having trouble reproducing the best results in your paper. I also think that the different data split makes it difficult to make a direct comparison. I would appreciate it if you could upload the data split file soon.
Thank you so much.

**Comment by leeh43** [comment]
Hi @paulwhz, sorry for the inconvenience. I will upload the .json script for the datasets. Do you mind you give me the email first? I can send you the dataset split for FLARE first, as I first organize it previously.

**Comment by paulwhz** [comment]
@leeh43 Sure, my email is eewenhaozhang@mail.scut.edu.cn. Thanks for your reply. I'm more focused on FeTA. Expect your future update!
