### ISSUE TITLE
AMOS2022 

### ISSUE THREAD

**Issue by pandajok** [MASILab/3DUX-Net#12]
Hello, thank you for sharing in the paper. I met some problems when training with amos2022 data set, could you help me solve them?
/3DUX-Net/networks/UXNet_3D/network_backbone.py
self.out = UnetOutBlock(spatial_dims=spatial_dims, in_channels=48, out_channels=self.out_chans)
TypeError: not all arguments converted during string formatting

**Comment by leeh43** [comment]
Thank you for your interest towards our paper and GitHub. The above comment is referring to the type of your arguments, which should be self.out_chans in string format. Please change to int(args.pretrain_classes) in model definition in main_finetune.py and see if it solves the problem or not.

**Comment by pandajok** [comment]
@leeh43 Thank you very much for your help, the code has been trained now!
