### ISSUE TITLE
Output Category Issues

### ISSUE THREAD

**Issue by ASmallWhit** [MASILab/3DUX-Net#13]
Hello, thank you for your work. I want to ask how to segment abdominal CT images with multiple categories, and how to output the dice score of each category at the same time? I don't think this is reflected in your code. Thank you very much

**Comment by leeh43** [comment]
Hi, thank you for your interest to our work! To segment abdominal CT images with multiple class (e.g., spleen, kidney, liver, ...etc), we define the number of classes (out_classes) that we want to segment. For instance, FLARE dataset have four organs labeled, so the number of classes will be 5 (number of organs + background).

For calculating the Dice score, we have leveraged a built-in function in MONAI (dice_metric) to compute the dice score across all categories. However, if you want to output the dice score of each category, you may need to use the dice_metric function for each prediction channel. You can first obtain the one-hot prediction of each channel and evaluation the overlapping region with the ground truth (also in one-hot setting). If you are still not familiar with it, I can send you my own dice score function.

**Comment by ASmallWhit** [comment]
> Hi, thank you for your interest to our work! To segment abdominal CT images with multiple class (e.g., spleen, kidney, liver, ...etc), we define the number of classes (out_classes) that we want to segment. For instance, FLARE dataset have four organs labeled, so the number of classes will be 5 (number of organs + background).
> 
> For calculating the Dice score, we have leveraged a built-in function in MONAI (dice_metric) to compute the dice score across all categories. However, if you want to output the dice score of each category, you may need to use the dice_metric function for each prediction channel. You can first obtain the one-hot prediction of each channel and evaluation the overlapping region with the ground truth (also in one-hot setting). If you are still not familiar with it, I can send you my own dice score function.

Thank you very much for your reply. I am a math major, but my programming ability is not enough to realize this idea by myself. If you can, I am looking forward to sending me a copy of the output of multi-category dice scores. Thank you very much.

**Comment by leeh43** [comment]
Got it. Do you mind to give me your email? I can send a .py file to you and let you see how I compute the dice score for each category.

**Comment by ASmallWhit** [comment]
Ok, thank you very much for your reply. My email is: ***@***.*** , looking forward to your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MASILab/3DUX-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月2日(星期四) 凌晨1:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MASILab/3DUX-Net] Output Category Issues (Issue #13)





 
Got it. Do you mind to give me your email? I can send a .py file to you and let you see how I compute the dice score for each category.

**Comment by leeh43** [comment]
I don't think that I can see your email. Here is my email: ho.hin.lee@vanderbilt.edu, feel free to reach out!

**Comment by ASmallWhit** [comment]
Hello, I didn't respond to the email I sent to you two days ago. If possible, could you send the code to the following email: ***@***.*** Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MASILab/3DUX-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月4日(星期六) 下午3:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MASILab/3DUX-Net] Output Category Issues (Issue #13)





 
I don't think that I can see your email. Here is my email: ***@***.***, feel free to reach out!

**Comment by CamillerFerros** [comment]
> Got it. Do you mind to give me your email? I can send a .py file to you and let you see how I compute the dice score for each category.

Hi @leeh43 can you please send me the .py file too? My email is [1226656132xb@gmail.com](mailto:1226656132xb@gmail.com). I am so interested in your work.Thanks!

**Comment by SanmAIGO** [comment]
Hi @leeh43 can you please send me the .py file too? My email is [[xiaosenforai@gmail.com](mailto:xiaosenforai@gmail.com)]. I am so interested in your work.Thanks!
