### ISSUE TITLE
How accurate is the direct training on amos2022?

### ISSUE THREAD

**Issue by Szc-coder** [MASILab/3DUX-Net#15]
Hello, thank you very much for your open source work. I want to ask how much precision can be achieved by training directly on amos2022 task1 instead of using fine tuning? Thank you!

**Comment by leeh43** [comment]
Hi, thank you for your interest! We have the training from scratch result in our upcoming paper in a few days. Will send you the link after we put to the arXiv.

**Comment by leeh43** [comment]
Our latest paper with the training from scratch scenario in AMOS 2022 is in https://arxiv.org/abs/2303.05785. Feel free to take a look and discuss with me if you have further comments or inquires.

**Comment by Szc-coder** [comment]
Thank you very much for your work. I have another question about how do you preprocess the amos dataset? Thank you.

**Comment by leeh43** [comment]
Please refer to the train_transform of AMOS dataset in the load_datasets_transforms.py. That is the preprocessing of how we prepare the input patches.

**Comment by Szc-coder** [comment]
Thank you for your patience.
