### ISSUE TITLE
About RuntimeError

### ISSUE THREAD

**Issue by zzzyzh** [MASILab/3DUX-Net#18]
Hi!

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

What should I do?

**Comment by leeh43** [comment]
Hi, seems like it is a mismatch with your pytorch and the cuda version. Have you followed my installation tutorial and install the corresponding version of pytorch?

**Comment by zzzyzh** [comment]
Yes I find that my env has some problems!
Thanks a lot!
