### ISSUE TITLE
dataset help

### ISSUE THREAD

**Issue by Yffy123456** [MASILab/3DUX-Net#2]
Would you like to know whether your FeTA data set is allocated according to the ratio of training verification test -80%, 10%, 10%? If so, is it randomly shuffled or placed in the training verification test set in order?

 Looking forward to your reply

**Comment by leeh43** [comment]
For both FeTA and FLARE datasets training scenario, we randomly shuffled samples with 5-fold cross validations using training (80%)/validation (10%)/testing (10%) split.

**Comment by Yffy123456** [comment]
Thanks
