### ISSUE TITLE
About warning

### ISSUE THREAD

**Issue by zzzyzh** [MASILab/3DUX-Net#21]
Hi,

I find that each step of validation throws a waring like this:
/root/miniconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/transforms/utils.py:500: UserWarning: N foreground 0, N  background 1713433,unable to generate class balanced samples.

What should I do?

**Comment by leeh43** [comment]
Hi, do you mind to print our which sample it is and look into the corresponding sample? Seems like your data contains all pixels/voxels as background.

**Comment by zzzyzh** [comment]
I think that my label is a little bit small that model only get bg after randomcrop. Do you think this is possible?

**Comment by leeh43** [comment]
Are you using the monai random crop function or the one that the current GitHub is using (Label crop)?

**Comment by zzzyzh** [comment]
Yes, I didn't change the code on your github, just the path and name

**Comment by leeh43** [comment]
Sorry for the late reply. If the label is so small, I believe it still can be cropped. But the above warning is telling us that there is no foreground within the label region. I believe you need to double check with the input label for training.

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
