### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by zjy359** [MASILab/3DUX-Net#22]
Hello, thank you very much for your work!!!

"Now I want to reproduce your code, but I can't find these three datasets online. Could you please share the datasets?"

**Comment by leeh43** [comment]
FeTA 2021: https://feta.grand-challenge.org/feta-2021/
FLARE 2021: https://flare.grand-challenge.org/
AMOS 2022: https://amos22.grand-challenge.org/

**Comment by xzhang123456** [comment]
Hello, @leeh43 ,thank you very much for your work!!! FeTA 2021: https://feta.grand-challenge.org/feta-2021/ is no found,AMOS 2022: https://amos22.grand-challenge.org/ not download ,Could you please share the datasets?",thank you

**Comment by hdnminh** [comment]
Hi @zjy359,

Could you share about your reproducing results? It will help a lot. Thank you so much
