### ISSUE TITLE
When changing the kernel size to 13, what parameter Settings should I change in the code?

### ISSUE THREAD

**Issue by clhbbd** [MASILab/3DUX-Net#23]
Dear big man, thank you for clearing my mind.

**Comment by leeh43** [comment]
Thank you for your interest towards our work. For kernel size of 13, I recommend to keep the current hyperparameters setting, as the performance is not yet saturated in the datasets with large field of view (such as whole body scans).

**Comment by clhbbd** [comment]
Thank you very much for your reply. Since the size of nucleus is the key research in this paper, I am also curious about how much impact the change of the size of nucleus will have on the segmentation effect if it is replaced with my current pancreas data set.

**Comment by leeh43** [comment]
Got it. Quick question, are your data inputs whole slide images? Seems like to segment nucleus, it should be a 2D image, instead of 3D (like CT, MRI).

**Comment by clhbbd** [comment]
Thank you for response. It's not the whole picture, it's a 3D CT image. It is the pancreas dataset. Because it is similar to the abdominal dataset in the paper, I want to test whether the size of 13 will change the performance.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MASILab/3DUX-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月21日(星期二) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MASILab/3DUX-Net] When changing the kernel size to 13, what parameter Settings should I change in the code? (Issue #23)





 
Got it. Quick question, are your data inputs whole slide images? Seems like to segment nucleus, it should be a 2D image, instead of 3D (like CT, MRI).

**Comment by leeh43** [comment]
For my personal comment, the performance may fluctuate with respect to the kernel size due to the difference field of view in the volumetric images. Therefore, I will recommend to begin with the kernel size of 7 and start scaling up to 13 (try 9, 11, 13) something like that. As you keep scaling up the kernel size, the performance will be saturated or even degraded. So it is a hyperparameter tuning process. If you want to see how we can feasibly leverage a very large kernel size, please take a look of our latest paper: http://128.84.21.203/abs/2303.05785

**Comment by clhbbd** [comment]
Thank you very much for your reply. I will read this paper&nbsp;carefully.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MASILab/3DUX-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 中午11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MASILab/3DUX-Net] When changing the kernel size to 13, what parameter Settings should I change in the code? (Issue #23)





 
For my personal comment, the performance may fluctuate with respect to the kernel size due to the difference field of view in the volumetric images. Therefore, I will recommend to begin with the kernel size of 7 and start scaling up to 13 (try 9, 11, 13) something like that. As you keep scaling up the kernel size, the performance will be saturated or even degraded. So it is a hyperparameter tuning process. If you want to see how we can feasibly leverage a very large kernel size, please take a look of our latest paper: http://128.84.21.203/abs/2303.05785
