### ISSUE TITLE
where is the batchgenerators function?

### ISSUE THREAD

**Issue by chunniunai220ml** [MASILab/3DUX-Net#24]
hi, thank for ur share, but i can not find batchgenerators module, can u help me how to fix?

![image](https://user-images.githubusercontent.com/17668109/226782746-613a5330-18ac-4d62-986b-4a64bfab4989.png)

**Comment by leeh43** [comment]
Thank you for your interest! Please install batchgenerators with pip: pip install batchgenerators

**Comment by chunniunai220ml** [comment]
> 

thank u, figured out
