### ISSUE TITLE
RuntimeError: Given groups=1, weight of size unmatch

### ISSUE THREAD

**Issue by chunniunai220ml** [MASILab/3DUX-Net#25]
![image](https://user-images.githubusercontent.com/17668109/227865536-27b426bb-a73a-44b3-a11f-a9479cc94892.png)

hi, the test_seg.py ,--dataset flare --network 3DUXNET ,i have tested last week ,is ok, but now it occurs weights unmatch, i see the hidden_size=768

**Comment by leeh43** [comment]
Have you modified the network design? If yes, do you mind to guide me that where have you changed?

**Comment by chunniunai220ml** [comment]
> 

nope, i just  git clone the repo, and follow the test insturction,
python test_seg.py --root ./labelsTs-public30/ --output res --dataset flare --network 3DUXNET --trained_weights  ./models/best_metric_model.pth --mode test --sw_batch_size 4 --overlap 0.7 --gpu 0 --cache_rate 0.2
i tested suceessfully last week,but it's wired that i met this bug, i see the network architecture is right

**Comment by leeh43** [comment]
Seems like your command is using labelsTs for input, instead of images?
