### ISSUE TITLE
training speed very slow is right?

### ISSUE THREAD

**Issue by yml-bit** [MASILab/3DUX-Net#26]
Hello, the utilization rate of GPU fluctuates continuously from 0 to 100%. Is the training speed very slow?

**Comment by leeh43** [comment]
Do you mind to tell me the time in tqdm bar for one epoch (The expected time for all batches)? I believe you are using kernel size of 7, so the training speed is slower than SwinUNETR, but it won't be too slow.

**Comment by yml-bit** [comment]
Thank you for your reply. What I mean is,  the GPU utilization is 1% for almost 2/3 of the time, and 100% for the rest of the time when I use NVIDIA 3090 to execute main_train.py training.

**Comment by leeh43** [comment]
I believe it will use around 14-15 GB memory during training if you keep using patches of 96x96x96, but it will increase when it comes to validation for the sliding window inference strategy in MONAI. If it is only 1% for most 2/3 of the time, it is pretty weird.
