### ISSUE TITLE
Problem reproducing results

### ISSUE THREAD

**Issue by mostafij-rahman** [MASILab/3DUX-Net#27]
Hi, thank you for your great work.  

We are having difficulty reproducing results on FETA 2021 and FLARE 2021 datasets. The reported average Dice score of FETA 2021 is **0.874** but we got an average Dice score of **0.813** (fold 1: 0.8871, fold 2: 0.7836, fold 3:  0.8558, fold 4:  0.7765, fold 5: 0.7642) using the default experimental setup of this GitHub repo. In FLARE 2021, we got an average Dice score of **0.926** (fold 1: 0.9372, fold 2: 0.9366, fold 3:  0.9148, fold 4:  0.9184, fold 5: 0.9239) but the reported Dice score is **0.934**.

Could you please share the folding you have? Or what should we do to reproduce the results?

Thanks,
Mostafij

**Comment by leeh43** [comment]
Thank you for your interest towards our work! Do you mind to give me your email address? I believe I can send you the FLARE data split first (As I organize it better first).

**Comment by mostafij-rahman** [comment]
Thanks for the prompt response. You can send them to _mostafijur.rahman@utexas.edu_. I am requesting you to share the FETA 2021 splits also as I significantly lower Dice score in this dataset. 

Thank you,
Mostafij

**Comment by zhangmk5** [comment]
> Thank you for your interest towards our work! Do you mind to give me your email address? I believe I can send you the FLARE data split first (As I organize it better first).

Hi @leeh43 can you please send me the FLARE data split too? My email is huiyuan440@gmail.com。Thanks!

**Comment by CamillerFerros** [comment]
> Thank you for your interest towards our work! Do you mind to give me your email address? I believe I can send you the FLARE data split first (As I organize it better first).

Hi @leeh43 can you please send me the FLARE data split too? My email is [1226656132xb@gmail.com](mailto:1226656132xb@gmail.com)。Thanks!

**Comment by xzhang123456** [comment]
Hi @leeh43  can you please send me the FLARE data split too? My email is zzw1322412@outlook. com   Thanks!

**Comment by cyuan031** [comment]
Hi @leeh43 can you please send me the FLARE data split too? My email is c1511442795@gmail.com Thanks!

**Comment by leeh43** [comment]
Hi @cyuan031, I have already pushed the flare dataset split as [dataset_FLARE.json](https://github.com/MASILab/3DUX-Net/blob/main/dataset_FLARE.json) to the GitHub.

**Comment by mostafij-rahman** [comment]
Thanks for updating the repo with AMOS and FLARE splits. Could you please upload the FETA splits?


Thanks,
Mostafij

**Comment by leeh43** [comment]
@mostafij-rahman Yes! Will do it afterwards.
