### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by xzhang123456** [MASILab/3DUX-Net#30]
Hello,thank you very much for your work！！！FeTA 2021: https://feta.grand-challenge.org/feta-2021/ is no found,AMOS 2022: https://amos22.grand-challenge.org/ not download ,Could you please share the datasets?",My email is jiaqi12300@gmail.com. com。 thank you very much.

thanks,
jiaqi

**Comment by leeh43** [comment]
Hi, have you joined the challenge? You need to join the challenge first, then you can get the access to download the data.

**Comment by xzhang123456** [comment]
ok,thank you very much
