### ISSUE TITLE
An error occurred during training

### ISSUE THREAD

**Issue by cyuan031** [MASILab/3DUX-Net#31]
Hi , thank you very much for your great work，I have meet some trouble when I train the amos dataset，it just shows ：
![1683630496409](https://github.com/MASILab/3DUX-Net/assets/133003365/d29509e6-f516-4421-b474-ff621c3f7383)
I wander why it happened，how to solove it

**Comment by leeh43** [comment]
Hi, thank you for your interest towards our work! Please change args.pretrain_classes with int(args.pretrain_classes) and it should be fine. Current error is referring that the args.pretrain_classes is in string format, not in int format for input.

**Comment by cyuan031** [comment]
Thank you for your answer. The problem has been resolved
