### ISSUE TITLE
AMOSS pretrained model

### ISSUE THREAD

**Issue by leoschopen** [MASILab/3DUX-Net#34]
Hi,thank you for your amazing work you have done on 3DUX-Net! I have been following your work for some time and have been impressed by the quality and impact of your research. Could you please send me your pretrained weights for AMOS 2022? leoschopen@gmail.com

**Comment by leeh43** [comment]
Hi thank you for your interest towards our work! Sorry for the late reply and the pretrained weights for AMOS and the data split for training and testing have been uploaded to the GitHub. Please take a look.

**Comment by leoschopen** [comment]
> Hi thank you for your interest towards our work! Sorry for the late reply and the pretrained weights for AMOS and the data split for training and testing have been uploaded to the GitHub. Please take a look.

thank you!
