### ISSUE TITLE
About the AMOS validation and the test_seg.py

### ISSUE THREAD

**Issue by Seconight** [MASILab/3DUX-Net#36]
Hello!
Thank you for your great work in 3DUX-Net! And I have a few questions:
I've seen the `dataset_AMOS.json` and there's 180 cases in Training and 20 cases in Test, and in the paper the ratio is 160:20:20. Are the 20 cases in the validation dataset randomly selected from the training set? Or are there other methods of splitting the training dataset?
And, I didn't find find the code for calculating the mean dice of each category and the total in the `test_seg.py`. Could you please provide specific code for calculating the metrics in the paper?
Thank you for your reply~

**Comment by leeh43** [comment]
Hi, thank you for your interest towards our work! I have tried the scenario of randomly sampled 20 cases for validation and the scenario of last 20 subjects (with last 20 subject numbers). Both demonstrates similar results and I would recommend to use the scenario of last 20 subjects.

For computing the Dice score, I have another python file to compute it and will upload to the GitHub afterwards.

**Comment by Seconight** [comment]
I got it! Thank you for your reply and work!
