### ISSUE TITLE
How to convert the model to onnx

### ISSUE THREAD

**Issue by ARnnn** [MASILab/3DUX-Net#38]
I trained my dataset with your model and achieved good results. But when I converted the trained Pytorch model into an Onnx model, I generated nearly 34% error. How can I convert the Pytorch model trained on a 3duxnet network into an Onnx model without losing accuracy

**Comment by leeh43** [comment]
Hi, thank you for your interest towards our work. It is a great question, as our initial thought does not include converting the model into a Onnx model. I can definitely look into it and see if I can help in the converting process.
