### ISSUE TITLE
I have some questions about this work

### ISSUE THREAD

**Issue by taylover12138** [MASILab/3DUX-Net#42]
Thank you very much for your research, it has helped me a lot! And,I have some questions I'd like to ask you.
When I read your paper, I was confused about this place: you labeled "3D UX-Net Block" on both of these drawings:
![屏幕截图 2023-07-19 204218](https://github.com/MASILab/3DUX-Net/assets/93075687/06ce2735-eace-4ecc-9610-bd9afa636413)![屏幕截图 2023-07-19 203957](https://github.com/MASILab/3DUX-Net/assets/93075687/68349e8b-7b8e-46cb-aa65-45f4faa7b70e)
But what I found is that they have different structures.
So I went through the code, and I realized that it just seemed to reflect what the first image was.
Can you help me solve this problem? I wonder if I misunderstood the code.
Thank you for your reply!

**Comment by leeh43** [comment]
Thank you for your interest and good question! The left one is the current block design in the code, while the right one is the illustrative and original idea by adapting the large kernel convolution with Swin Transformer backbone. As the performance here only have subtle changes with both of the design in the datasets that we evaluated, I directly go for a more simple design in the code, but definitely I can provide the code from the right design to the GitHub. Sorry for the confusion.

**Comment by taylover12138** [comment]
> Thank you for your interest and good question! The left one is the current block design in the code, while the right one is the illustrative and original idea by adapting the large kernel convolution with Swin Transformer backbone. As the performance here only have subtle changes with both of the design in the datasets that we evaluated, I directly go for a more simple design in the code, but definitely I can provide the code from the right design to the GitHub. Sorry for the confusion.

OK！I got it! Thank you very much for your reply! At the same time, thank you and your work, which let me learn a lot!
