### ISSUE TITLE
Loop when trying to train model

### ISSUE THREAD

**Issue by refrantz** [MASILab/3DUX-Net#43]
Hello, I'm trying to train your model on another dataset and after caching the dataset it starts a loop and starts caching the dataset again. Here is an example of what I'm talking about:

![Screenshot 2023-07-20 172504](https://github.com/MASILab/3DUX-Net/assets/21325029/91307dfd-317c-4c92-88ea-c7c78bcc9006)

This also happens when downloading the amos22 dataset and trying to train on that (don't have the screenshot but it's literally the same problem)

Any help is appreciated, thanks in advance.

**Comment by leeh43** [comment]
Hi, thank you your interest towards our work. I am sure that our work is working, as I have tried so many times, and also only a paragraph of code is for dataloader as follows:
![image](https://github.com/MASILab/3DUX-Net/assets/54121206/829689d5-5f21-447d-ba01-982586e387b1)

Have you changed any code in main_train.py?

**Comment by refrantz** [comment]
I haven't, only changed code in load_datasets_transforms.py. Am I correct in understanding that to add my dataset I need to include it with the correct folder structure in root_dir, and edit load_datasets_transforms.py so it sets the number of output channels correctly and applies the transforms?

I'll keep trying, if I'm adding the datasets correctly it's probably something with my enviroment. Thanks.

**Comment by leeh43** [comment]
Seems like you are using windows terminal to train it. Do you mind to switch to WSL2 to train it? Maybe there are some incompatibilities behind that, as my code is written under ubuntu system. 

But this phenomenon is pretty weird I can say, and I think that you are doing correctly, only changing the load_datasets_transforms.py and haven't changed anything in main_train.py.

**Comment by refrantz** [comment]
That actually worked, seems like it was something with windows indeed. Thanks for the help.
