### ISSUE TITLE
There are discrepancies between the network architecture and the code.

### ISSUE THREAD

**Issue by clhbbd** [MASILab/3DUX-Net#45]
Upon comparing the network architecture in this article with the network diagram formed by the code, I noticed significant differences. For example, the code includes only four instances of downsampling, four instances of upsampling, and four instances of skip connections, which do not align with the network diagram provided in the article. I apologize for raising this question and I would appreciate it if you could reply.

**Comment by leeh43** [comment]
Thank you for your interest towards our work! We directly leverage the SwinUNETR-like architecture as our backbone and only change the encoder part. The final downsampling block is performed in self.encoder5 in network_backbone.py. Also, I have some adjustment of adapting the first skip connection in the figure, as the performance only have a subtle varies from 0.936 to 0.938 with FLARE dataset, but definitely you can give it a try.

**Comment by clhbbd** [comment]
Thank you very much for your reply. ok, I will try again.

**Comment by hdnminh** [comment]
Hi @clhbbd,

Have you tried it? Can you tell me the results and whether there are any significant variations?
