### ISSUE TITLE
labels convert

### ISSUE THREAD

**Issue by quxianjiuguo** [MASILab/3DUX-Net#48]
How to convert labels to 0,1,2,3,...
because it goes wrong with "RuntimeError: index 550 is out of bounds for dimension 1 with size 8"
550 is a label pixel value in my medical data and my numclass is 8

**Comment by leeh43** [comment]
Thank you for your interest to our work. Just want to have more context, I am wondering what you are trying to segment, because 550 should not be a label value and it should be an image pixel value. As your channel size is 8 only, it mismatch your real value with your input.
