### ISSUE TITLE
训练过程中到验证阶段出现显卡内存不足问题

### ISSUE THREAD

**Issue by guli-7721** [MASILab/3DUX-Net#50]
我微调了一下代码，让模型用两个显卡跑，还是会出现显卡内存不足情况 。
把 max_iter 设为10万，eval_step设为1000，batch_size设为1，num_workers 设为0，用两张显卡跑也出现了显卡内存不足情况，但明明显示两个显卡内存分别占用7G左右，显卡是有充足的内存，不知什么原因了，请教您一下各位大佬解决问题的方法 ，谢谢！

![image](https://github.com/MASILab/3DUX-Net/assets/139946751/74be4a8a-abd2-4f16-8c95-17c9e765c362)

**Comment by landonmax0** [comment]
求问怎么设置多显卡运行，需要改哪里？

**Comment by dream-mjq** [comment]
I have the same problem, have you solved this problem?

**Comment by guli-7721** [comment]
I solved it, if you put your own dataset and you need to change the dataset name, remember that it's in load_dataset_transforms.py, flare change it to your own dataset name.
I hope you find the above answer helpful!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MASILab/3DUX-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月9日(星期二) 晚上9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MASILab/3DUX-Net] 训练过程中到验证阶段出现显卡内存不足问题 (Issue #50)





 
I have the same problem, have you solved this problem?

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.

**Comment by RY-97** [comment]
> 我微调了一下代码，让模型用两个显卡跑，还是会出现显卡内存不足情况 。 把 max_iter 设为10万，eval_step设为1000，batch_size设为1，num_workers 设为0，用两张显卡跑也出现了显卡内存不足情况，但明明显示两个显卡内存分别占用7G左右，显卡是有充足的内存，不知什么原因了，请教您一下各位大佬解决问题的方法 ，谢谢！
> 
> ![image](https://private-user-images.githubusercontent.com/139946751/259323814-74be4a8a-abd2-4f16-8c95-17c9e765c362.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDQyODAsIm5iZiI6MTcyNTg0Mzk4MCwicGF0aCI6Ii8xMzk5NDY3NTEvMjU5MzIzODE0LTc0YmU0YThhLWFiZDItNGYxNi04Yzk1LTE3YzllNzY1YzM2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMTA2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDZjMzY3YjU1ZmRlYzFlMzdlYjA4MTc5MTM0MmYyNTAxZWU4NzJlZTIyNWQ5ZmIzZWQxZWMwNWU5Mjk5NjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qU-yzcFM0ZUQqPxgl7sCzx74RGF6NjaMZblzG_Vz-aA)

请问您有完整的修改代码吗？这个原始代码错误的地方太多了？

**Comment by RY-97** [comment]
@guli-7721
