### ISSUE TITLE
Is there a missing fifth downsampling block in the code, 384->768？

### ISSUE THREAD

**Issue by AN-AN-369** [MASILab/3DUX-Net#51]
I'm glad to have read your paper; the ideas presented are quite innovative. However, while going through your code, I came across an issue. I can't find the fourth downsampling block in the code, 384->768。

**Comment by leeh43** [comment]
Hi, thank you your interest to our work. The fifth block is in the network_backbone.py and please take a look of the screenshot as follows:

![image](https://github.com/MASILab/3DUX-Net/assets/54121206/ad313b93-dc21-4125-9668-c385f5153778)
![image](https://github.com/MASILab/3DUX-Net/assets/54121206/ee3bfadb-f05d-4a30-a86e-d4bf0be0f41c)

**Comment by AN-AN-369** [comment]
Thank you very much for your response. I still have a question. I understand that this diagram represents the 3D UX-Net block, corresponding to the 'ux_block' function in the code. 
![image](https://github.com/MASILab/3DUX-Net/assets/65226022/d6417265-ed9a-41f7-815a-07ce344a2938)
However, I find it a bit difficult to understand the 3D UX-Net module in Figure 2, and there doesn't seem to be a corresponding part in the code.
![image](https://github.com/MASILab/3DUX-Net/assets/65226022/d27b5520-2ee1-4539-9f3d-90675da0c8c7)

**Comment by LambdaLi** [comment]
I think there is no fourth down sampling at all. I guess the author used the fourth stage as a bottleneck and directly went up sampling after enc5.

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
