### ISSUE TITLE
I encountered an error while using the Inverted() function in the input_ Post_ Transforms  .  But I commented out the Inverted() function, and the inference method can run normally

### ISSUE THREAD

**Issue by quxianjiuguo** [MASILab/3DUX-Net#52]
![捕获1](https://github.com/MASILab/3DUX-Net/assets/72400883/5064ebaf-0c89-42cb-ba77-ab4d2b19d7aa)
![image](https://github.com/MASILab/3DUX-Net/assets/72400883/546e546f-ba92-43c2-b9fc-7f846406c637)

**Comment by leeh43** [comment]
Hi thank you for your interest towards our work. Just want to make sure with you, have you followed the instruction in INSTALL.md to install correct version of MONAI?

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
