### ISSUE TITLE
换成自己的数据集（512*521*20的3d核磁影像）后训练报错如下，想请教一下如何修改？另一个问题是：Number of classes for segmentation: 2能否使用amos(number of classes:16)的预训练权重？非常感谢！

### ISSUE THREAD

**Issue by s-j-y1** [MASILab/3DUX-Net#53]
<img width="1076" alt="1" src="https://github.com/MASILab/3DUX-Net/assets/123573511/8d3b9f2f-c228-48a0-8b06-dab2c0e3d163">

<img width="814" alt="2" src="https://github.com/MASILab/3DUX-Net/assets/123573511/0bf03431-5dd1-463d-9962-2f7259b01972">

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
