### ISSUE TITLE
 5-Fold Cross-Validation

### ISSUE THREAD

**Issue by AN-AN-369** [MASILab/3DUX-Net#54]
Hi,thank you for your amazing work you have done on 3DUX-Net! 
After reading your code, I did not find the part of the 5-Fold Cross-Validation. If possible, could you give me a hint of the location of the 5-Fold Cross-Validation code?

**Comment by llyyyll** [comment]
Hello, I have the same problem after reading the code，have you found the code for  5-Fold Cross-Validation now?

**Comment by coastcode** [comment]
same problem here

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.

**Comment by kingofstu** [comment]
> Hi,thank you for your amazing work you have done on 3DUX-Net! After reading your code, I did not find the part of the 5-Fold Cross-Validation. If possible, could you give me a hint of the location of the 5-Fold Cross-Validation code?

Hello, heve you slove this problem?

**Comment by kingofstu** [comment]
> Hello, I have the same problem after reading the code，have you found the code for 5-Fold Cross-Validation now?

Hello, have you solve this problem?

**Comment by kingofstu** [comment]
> same problem here

Hello, have you solve this problem?
