### ISSUE TITLE
Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by OCEANOUXIN** [MASILab/3DUX-Net#56]
Hi! Thanks for your exellcent work.But when I run _main_train.py_,I got 
__Traceback (most recent call last):_

  __File ~/anaconda3/envs/nunet/lib/python3.8/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)_

  _File /home2/ouxin/3DUX-Net-main/main_train.py:252
    global_step, dice_val_best, global_step_best = train(_

  _File /home2/ouxin/3DUX-Net-main/main_train.py:198 in train
    loss.backward()_

  _File ~/anaconda3/envs/nunet/lib/python3.8/site-packages/torch/_tensor.py:355 in backward
    return handle_torch_function(_

  _File ~/anaconda3/envs/nunet/lib/python3.8/site-packages/torch/overrides.py:1394 in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)_

  _File ~/anaconda3/envs/nunet/lib/python3.8/site-packages/monai/data/meta_tensor.py:276 in __torch_function__
    ret = super().__torch_function__(func, types, args, kwargs)_

  _File ~/anaconda3/envs/nunet/lib/python3.8/site-packages/torch/_tensor.py:1142 in __torch_function__
    ret = func(*args, **kwargs)_

  _File ~/anaconda3/envs/nunet/lib/python3.8/site-packages/torch/_tensor.py:363 in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)_

  _File ~/anaconda3/envs/nunet/lib/python3.8/site-packages/torch/autograd/__init__.py:173 in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass__

_RuntimeError: Unable to find a valid cuDNN algorithm to run convolution__

It seems that the _loss.backward()_ gose wrong. Have you ever meet it? I don't know how to fix it. 
I have checked the CUDA 11.3 and cuDNN 8.2.0.
If you know how to fix it, please let me know. Thanks.

**Comment by gg336699** [comment]
Hello,Have you solved this problem?

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
