### ISSUE TITLE
Finetuning on heart dataset with 8 classes.

### ISSUE THREAD

**Issue by gautamb2222** [MASILab/3DUX-Net#57]
I am working on a project to segment heart parts, as the data I have is limited, I finalised to finetune model on weights I got by training on FLare datset. While doing that I am having some errors attached below. Just to check if fine-tuning works fine for amos as mentioned by you, I tried finetuning with amos dataset as well, for which again I am gettting error after few iterations:

**ERROR ON AMOS AFTER 131 iterations:**
<img width="958" alt="Screenshot 2023-11-06 at 5 59 16 PM" src="https://github.com/MASILab/3DUX-Net/assets/84632454/0fc482b1-585f-4909-81e1-60e1568edd1c">

**ERROR ON HEART DATASET, for which finetuning didn't even start:**
<img width="1674" alt="image" src="https://github.com/MASILab/3DUX-Net/assets/84632454/7f09b1af-b9fd-439b-92b3-3f999a74dfc5">
I am using --dataset as feta here because feta does have the same number of classes as heart dataset(in my case) and I am expecting same transforms as for feta to work for my case as well. I tried changing transforms but can't get this thing right and leading to more new errors changing anything.

**Please suggest me something which might be helpful for me, I am just trying to get a baseline from your implementation.**

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
