### ISSUE TITLE
dataset josn issue

### ISSUE THREAD

**Issue by Qsaywaitwait** [MASILab/3DUX-Net#61]
why your josn file don't have val dateset?

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.

**Comment by landonmax0** [comment]
I hava the same question

**Comment by kingofstu** [comment]
> why your josn file don't have val dateset?

Hello, have you solve this problem?
