### ISSUE TITLE
Size mismatch problem in training AMOS2022 dataset

### ISSUE THREAD

**Issue by chenyucong1** [MASILab/3DUX-Net#62]
Hello, thank you for your excellent work. In the process of training AMOS data set, I encountered a mismatch between the roi image size and the label size, may I ask how to solve it?
![0b922e7d4155af38609f577815574a2](https://github.com/MASILab/3DUX-Net/assets/80387024/9335c817-114d-4070-8166-a262635fb665)
![7f2baf07249b15eb41287b339e99208](https://github.com/MASILab/3DUX-Net/assets/80387024/164ad77b-8097-4334-9433-cdf8ffa88fb8)
![cfb11ccd00482a5d02dcca3e8d761de](https://github.com/MASILab/3DUX-Net/assets/80387024/753f9ef5-09b8-4c1e-9afb-6380d4c5fc68)

**Comment by landonmax0** [comment]
Hello, I have also encountered the same problem. How did you solve it?

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
