### ISSUE TITLE
TypeError: _VariableFunctionsClass.meshgrid() got multiple values for keyword argument 'indexing'

### ISSUE THREAD

**Issue by wzh0328** [MASILab/3DUX-Net#63]
May I ask why there will be mistakes in training？
TypeError: _VariableFunctionsClass.meshgrid() got multiple values for keyword argument 'indexing'

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
