### ISSUE TITLE
Size problem of input model

### ISSUE THREAD

**Issue by chaixiaoyi2** [MASILab/3DUX-Net#64]
Hi, I'm very interested in your work. I want to use it for my airway segmentation. I use amos for data processing, but only the trunk of the airway can be separated at present. I want to modify the size of the input picture, but I keep reporting errors, may I ask how to modify the input size?
 In addition, do you have any other suggested changes for this 3D CT image of the airway segmentation with small branches?Such as preprocessing or parameters and so on.
![1](https://github.com/MASILab/3DUX-Net/assets/44825884/29b5b542-7839-4d36-b009-69c2bda87a4c)
![Uploading 2.png…]()

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
