### ISSUE TITLE
Validation Segmentation Loss naming error

### ISSUE THREAD

**Issue by tingwei161803** [MASILab/3DUX-Net#65]
In main_train.py
line  180-182
    mean_dice_val = np.mean(dice_vals)
    writer.add_scalar('Validation Segmentation Loss', mean_dice_val, global_step)
    return mean_dice_val

I think there is a naming error, which name the dice value to loss

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
