### ISSUE TITLE
Can this code be used for tumor lesion segmentation

### ISSUE THREAD

**Issue by nekonekoni7** [MASILab/3DUX-Net#67]
Can this code be used for tumor lesion segmentation, such as segmenting lung cancer lesions from CT images of the whole body. Looking forward to a reply.

**Comment by tingwei161803** [comment]
In my experience, the answer is "yes," but you'll need to modify some code to fit your dataset.

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
