### ISSUE TITLE
Big problem

### ISSUE THREAD

**Issue by GitHub-TXZ** [MASILab/3DUX-Net#69]
Your figure is not consistent to your code. There are 5 stages in your figure while only 4 stages in your code.  Futhermore, the downsampling should be ahead of UX-Net block.

**Comment by 2345678y3** [comment]
> 您的图与代码不一致。图中有 5 个阶段，而代码中只有 4 个阶段。此外，下采样应先于 UX-Net 模块。
debug了下 图片是32倍下采样，但是他实际只有16倍下采样，原版3dunet也是只有16倍

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
