### ISSUE TITLE
erros using SWINUNETR

### ISSUE THREAD

**Issue by ramdhan1989** [MASILab/3DUX-Net#70]
Hi, 
I got error when using SWINUNETR, my input size to the model is 4,1,96,96,96. When changing to 3DUXNET it works.

> raise ValueError("Expected more than 1 spatial element when training, got input size {}".format(size))
> ValueError: Expected more than 1 spatial element when training, got input size torch.Size([4, 768, 1, 1, 1])

please advise,

Thank you

**Comment by landonmax0** [comment]
hello, i am  using SWINUNETR too, but i can't properly run it yet. 

RuntimeError: CUDA error: out of memory CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

same configuration, run 3d-uxnet is ok, but run  SWINUNETR is error........Could you tell me how to handle this?

**Comment by landonmax0** [comment]
> ramdhan1989
hello@, i am  using SWINUNETR too, but i can't properly run it yet. 

RuntimeError: CUDA error: out of memory CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

same configuration, run 3d-uxnet is ok, but run  SWINUNETR is error........Could you tell me how to handle this?

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
