### ISSUE TITLE
Flare 2021 kidney

### ISSUE THREAD

**Issue by quxianjiuguo** [MASILab/3DUX-Net#71]
![image](https://github.com/MASILab/3DUX-Net/assets/72400883/e1e12e50-264d-4e4c-aef9-3258dd62c941)
Hello, I used your model to train on Flare2021, but the inference result seems to be missing something (Kidney miss). Can you help me solve the problem

**Comment by JinYangprominent1994** [comment]
How many labels did you infer? It has (0, 1, 2, 3, 4).

**Comment by JinYangprominent1994** [comment]
How did you crop ROI randomly in this dataset. Some image volume has smaller size than (96, 96, 96).

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
