### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by tzungyo** [MASILab/3DUX-Net#73]
![螢幕擷取畫面 2024-03-15 005435](https://github.com/MASILab/3DUX-Net/assets/158141789/6b16095c-27ad-4b09-87fa-21717db8d8aa)
how can i solve this problem
I want to run my own data. Which part of the code do I need to modify?
Best regard,
Andrew

**Comment by 975827738** [comment]
I think you did not fill in the address of the file including root, output, etc. May I ask if it has been solved now

**Comment by tzungyo** [comment]
I have set my address but it still show the same problem
![螢幕擷取畫面 2024-04-15 011010](https://github.com/MASILab/3DUX-Net/assets/158141789/1d2744e8-ef77-4dae-8b62-e9fa2c94ed54)
best regard ,
Andrew

**Comment by 975827738** [comment]
> I have set my address but it still show the same problem ![螢幕擷取畫面 2024-04-15 011010](https://private-user-images.githubusercontent.com/158141789/322290614-1d2744e8-ef77-4dae-8b62-e9fa2c94ed54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzYwNDgsIm5iZiI6MTcxMzE3NTc0OCwicGF0aCI6Ii8xNTgxNDE3ODkvMzIyMjkwNjE0LTFkMjc0NGU4LWVmNzctNGRhZS04YjYyLWU5ZmEyYzk0ZWQ1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxMDA5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmVmYTFkNGI3YTZhY2M3MjhmZmUzNTg2ODJjM2YzOGNkMmIwMDY5OTllNmRmNGUyMGM1MGMxOThmZDNjOGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n46fffC-QFVQGPSqzFhP3YZNp1xUNUfNlSiL-fC9DaU) best regard , Andrew

The correct approach should be to fill in the root in the default field
like this:
parser.add_argument('root',default='C:\\Users\\andre\\
![Uploading 1.png…]()
')

**Comment by 975827738** [comment]
> I have set my address but it still show the same problem ![螢幕擷取畫面 2024-04-15 011010](https://private-user-images.githubusercontent.com/158141789/322290614-1d2744e8-ef77-4dae-8b62-e9fa2c94ed54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzYyOTcsIm5iZiI6MTcxMzE3NTk5NywicGF0aCI6Ii8xNTgxNDE3ODkvMzIyMjkwNjE0LTFkMjc0NGU4LWVmNzctNGRhZS04YjYyLWU5ZmEyYzk0ZWQ1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxMDEzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmU3MWI2OTU0MjRkNzdmMmI1NDFmNDA1MDQzYmZiYmViY2EzZjUyNTU4Y2ExZTQ1YTM3ZTE2M2YyYmZlMzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eejpdg_rGCeVm7xDh2jDlYJy2_ZGeCxnA3uPbjSgy58) best regard , Andrew

![Uploading 1.png…]()
