### ISSUE TITLE
Some confusion in using validation sets

### ISSUE THREAD

**Issue by landonmax0** [MASILab/3DUX-Net#74]
The 3 Json file just mentioned training and testing sets, but nothing about validation sets. Is validation sets was used in the project? or is it necessry?

I saw in other issues that you mentioned the validation set, but how should we configure and use the validation set specifically? Do I need to rewrite the JSON file?

(Training FLARE2021)

**Comment by aixiaobaikkk** [comment]
I have the same question...

**Comment by BennettLandman** [comment]
Please contact the corresponding author: ho.hin.lee@Vanderbilt.Edu

**Comment by kingofstu** [comment]
> The 3 Json file just mentioned training and testing sets, but nothing about validation sets. Is validation sets was used in the project? or is it necessry?
> 
> I saw in other issues that you mentioned the validation set, but how should we configure and use the validation set specifically? Do I need to rewrite the JSON file?
> 
> (Training FLARE2021)

Hello, have you solve this problem?

**Comment by kingofstu** [comment]
> I have the same question...
Hello, have you solve this problem?
