### ISSUE TITLE
ValueError: axcodes must match data_array spatially, got axcodes=3D data_array=4D

### ISSUE THREAD

**Issue by dream-mjq** [MASILab/3DUX-Net#75]
![image](https://github.com/MASILab/3DUX-Net/assets/84175712/5e27a85b-0708-468a-8722-ec0716560990)

If I follow github's instructions and then use the provided amos2022 dataset, what happens?

**Comment by RY-97** [comment]
> ![image](https://private-user-images.githubusercontent.com/84175712/320267358-5e27a85b-0708-468a-8722-ec0716560990.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDMzNjgsIm5iZiI6MTcyNTg0MzA2OCwicGF0aCI6Ii84NDE3NTcxMi8zMjAyNjczNTgtNWUyN2E4NWItMDcwOC00NjhhLTg3MjItZWMwNzE2NTYwOTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAwNTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MGMzYTE3YjM1NzNmZDdiMzkwMzcwNjdkZTFkZmFhZmVmYjYwNTI3YTFmMjk0ZjdkZjNmYzAwZGVkYmZkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5oEzdi4K_iI_2BQjJGfWT7R0JOckcUMVQ51wy63sUas)
> 
> If I follow github's instructions and then use the provided amos2022 dataset, what happens?

Has your issue been resolved? Can you contact me? I want to ask you some questions
