### ISSUE TITLE
Dear author, I want to know why the dataset division in the paper is inconsistent with dataset_FLARE.json.

### ISSUE THREAD

**Issue by aixiaobaikkk** [MASILab/3DUX-Net#77]
Why is it so divided? I want to compare with your text, but I can't find the data set of 511 cases. I only found 361 cases. Can I divide it in the same way as you? In addition, are you using subtask1 or subtask? Please help me answer it. I will be very grateful.

**Comment by BennettLandman** [comment]
Please contact the corresponding author: ho.hin.lee@Vanderbilt.Edu
