### ISSUE TITLE
UnetrBasicBlock vs UX-net block

### ISSUE THREAD

**Issue by dirtycomputer** [MASILab/3DUX-Net#8]
why all encoder in 3dux-net all use UnetrBasicBlock instead of the module you mentioned in paper?

**Comment by ikboljon** [comment]
Hi there, @dirtycomputer . I am not the author of the code, but I am reading the code and might have an answer to your question. UnetrBasicBlock is defined as an encoder, but it is actually the CNN block in the skip connections that takes in the Transformer Block outputs and reshapes. That is to be able to concatenate back with the upsampling path blocks.

**Comment by leeh43** [comment]
Hi, thank you for the interest towards the network structure. @ikboljon have provided a correct general view of using the UnetrBasicBlock. The UnetrBasicBlock is used to downsample the features and fuse the decoder feature as skip connections, which is similar to the original 3D UNet structure, but with resnet block as skip connections.

**Comment by dirtycomputer** [comment]
Thanks
