### ISSUE TITLE
why your josn file don't have val dateset?

### ISSUE THREAD

**Issue by landonmax0** [MASILab/3DUX-Net#80]
Moreover, the allocation ratio of the flare dataset in the JSON file is different from that in the paper. 
Only training and testing split in your json file.

**Comment by landonmax0** [comment]
Moreover, the allocation ratio of the flare dataset in the JSON file is different from that in the paper.

**Comment by BennettLandman** [comment]
Please contact the lead author who has left Vanderbilt.

**Comment by kingofstu** [comment]
> Moreover, the allocation ratio of the flare dataset in the JSON file is different from that in the paper. Only training and testing split in your json file.

Hello, have you solve this problem?
