### ISSUE TITLE
FLare2021 dataset

### ISSUE THREAD

**Issue by kimjisoo12** [MASILab/3DUX-Net#9]
Hello, thank you for your work. I read that you used a total of 511 flare 2021 datasets in the article, but I only saw 361 data and 50 unlabeled validation sets from the official website. I wonder if you could share all the flare 2021 datasets with me.
    
Thank you very much

**Comment by leeh43** [comment]
Thank you for your interest towards our work. Sorry for the confusion in the dataset, we only use 361 samples with ground truth label to perform 5-fold cross validation. Please take a look the dataset details in the Appendix and I will further fix it in the latest version of the manuscript.
